# Generated by Django 4.2.4 on 2023-09-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
